//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeTracker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name can contain only alphanumeric characters and these special characters: {0}.
        /// </summary>
        internal static string Application_categoryToolTip_Text {
            get {
                return ResourceManager.GetString("Application_categoryToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete entries.
        /// </summary>
        internal static string Application_deleteMessageBox_Caption {
            get {
                return ResourceManager.GetString("Application_deleteMessageBox_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You sure want to delete {0} entries?.
        /// </summary>
        internal static string Application_deleteMessageBox_Message {
            get {
                return ResourceManager.GetString("Application_deleteMessageBox_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File error.
        /// </summary>
        internal static string Application_fileErrorMessageBox_Caption {
            get {
                return ResourceManager.GetString("Application_fileErrorMessageBox_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an error while handling a file..
        /// </summary>
        internal static string Application_fileErrorMessageBox_Message {
            get {
                return ResourceManager.GetString("Application_fileErrorMessageBox_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech.
        /// </summary>
        internal static string Application_language_cs {
            get {
                return ResourceManager.GetString("Application_language_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;default&gt;.
        /// </summary>
        internal static string Application_language_default {
            get {
                return ResourceManager.GetString("Application_language_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Application_language_en {
            get {
                return ResourceManager.GetString("Application_language_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language changed.
        /// </summary>
        internal static string Application_languageChangedMessageBox_Caption {
            get {
                return ResourceManager.GetString("Application_languageChangedMessageBox_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The change will take effect once the application restarts..
        /// </summary>
        internal static string Application_languageChangedMessageBox_Message {
            get {
                return ResourceManager.GetString("Application_languageChangedMessageBox_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no tracking data yet. Start tracking by using the buttons above or opening a new file..
        /// </summary>
        internal static string Application_noDataLabel {
            get {
                return ResourceManager.GetString("Application_noDataLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist.
        /// </summary>
        internal static string Application_nonexistentFileMessageBox_Caption {
            get {
                return ResourceManager.GetString("Application_nonexistentFileMessageBox_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load specified file because it does not exist..
        /// </summary>
        internal static string Application_nonexistentFileMessageBox_Message {
            get {
                return ResourceManager.GetString("Application_nonexistentFileMessageBox_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category &quot;{0}&quot;: {1}.
        /// </summary>
        internal static string Application_statsCategory_Text {
            get {
                return ResourceManager.GetString("Application_statsCategory_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection ({0}): {1}.
        /// </summary>
        internal static string Application_statsSelected_Text {
            get {
                return ResourceManager.GetString("Application_statsSelected_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {0}.
        /// </summary>
        internal static string Application_statsTotal_Text {
            get {
                return ResourceManager.GetString("Application_statsTotal_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string Application_unsavedMessageBox_Caption {
            get {
                return ResourceManager.GetString("Application_unsavedMessageBox_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes. Save now?.
        /// </summary>
        internal static string Application_unsavedMessageBox_Message {
            get {
                return ResourceManager.GetString("Application_unsavedMessageBox_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] clock1 {
            get {
                object obj = ResourceManager.GetObject("clock1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_delete {
            get {
                object obj = ResourceManager.GetObject("icon_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
